### ISSUE TITLE
fseek state in FCB probably not initialized

### ISSUE THREAD

**Issue by nero** [dmsc/emu2#20]
Original problem:

Some files openend via the default FCB at 0x5C open successfully, but the first read with int 21h/ah=14h fails with al=01h (eof signal), despite the file having several records full of data.

I tracked this problem down to `dos_read_record_fcb(int addr, int update)`, where `unsigned pos = rsize * get32(0x21 + fcb);` is reading seemingly garbage data, resulting in `if(fseek(f, pos, SEEK_SET))` to set the read pointer behind the end of the file.

```
lseek(3, 0, SEEK_END)                   = 316
lseek(3, 0, SEEK_CUR)                   = 316
lseek(3, 0, SEEK_SET)                   = 0
lseek(3, 2147483648, SEEK_SET)          = 2147483648
readv(3, [{iov_base="", iov_len=127}, {iov_base="", iov_len=1024}], 2) = 0
```

I did only find two places where the 32-bit value at FCB+0x21 is written to, in the same function below and the equivalent in the `dos_write_record_fcb`, both are not reachable with the fseek failing beforehand.

Unaware of the right solution, i made the behavior disappear by initializing the value to zero during the int 21h/ah=0fh open call with the following patch:

```
diff --git a/src/dos.c b/src/dos.c
index 3d916e5..09fcc79 100644
--- a/src/dos.c
+++ b/src/dos.c
@@ -318,6 +318,7 @@ static void dos_open_file_fcb(int create)
     put16(fcb_addr + 0x16, 0);   // time of last write
     put16(fcb_addr + 0x18, h);   // reserved - store DOS handle!
     memory[fcb_addr + 0x20] = 0; // current record
+    put32(fcb_addr + 0x21, 0);   // fseek position
 
     debug(debug_dos, "OK.\n");
     cpuClrFlag(cpuFlag_CF);
```

Can you use this information to detect where this problem comes from?

I'm at loss why this only happens for a few files. I attached [NASM code](https://github.com/dmsc/emu2/files/7112220/test.asm.txt) that fails to read [this file](https://github.com/dmsc/emu2/files/7112221/a86.txt). Exact commands that i used to reproduce: `nasm -o test.com test.asm.txt` and `emu2 test.com a86.txt`.

My system is alpine linux 3.15, running the musl-1.2.2 libc and manually compiled emu2 from gitrev c03b12c84c8 (current master).

**Comment by dmsc** [comment]
Thank you for your very well researched bug report!

I investigated a little more, and there is another subtle bug:
- On function 14h and 15h (sequential read/write using FCB), the code should read/write from current position expressed in blocks, not from the "random position".
- On functions 21h, 22h, 27h and 28h (random/block read/write using FCB), the code should read/write from the "random position" as set by the user.

Now, your fix works because it sets the "random position" when the file is open, and the reading is correct. But that fix would not work if the user application sets the record number before calling the read function.

I implemented the correct behavior for the 14h and 15h functions. I don't know if it is really necessary to initialize to 0 the random position field, but I  added it nevertheless.

Again, thank you very much for your report.

**Comment by nero** [comment]
This morning i noticed something. The 32-bit value is 4 bytes wide. The end of the FCB structure is at 0x5C (1st def FCB) + 0x21 + 4 at 0x81, which is 1 byte into the DTA/cmdline. This overwrites the size of the command line arguments :/

**Comment by dmsc** [comment]
Hi!

> This morning i noticed something. The 32-bit value is 4 bytes wide. The end of the FCB structure is at 0x5C+0x21+4 at 0x81, which is 1 byte into the DTA/cmdline. This overwrites the size of the command line arguments :/

Yes, that is why your code sometimes worked: it was faulty whenever the command line was less than 8 bytes.
And my fix was not really working, as you discovered the DTA was being overwritten, with the last byte of the FCB.

**Comment by dmsc** [comment]
I have a test program, and made changes to the emulator so that the behavior is the same as MS-DOS 1.0 up to DOS 5.0. Attached is the test program and this is the images of the output on real DOS versions:

![dos10](https://user-images.githubusercontent.com/5713395/132363336-f402a4fc-ae0d-41b2-9d0b-ab7e103619cf.png)
![dos33](https://user-images.githubusercontent.com/5713395/132363346-1e28f8cb-caa1-409c-a3c5-6574ab0128c5.png)
![dos21](https://user-images.githubusercontent.com/5713395/132363352-12ef33f8-c4a2-4cb5-9154-94afb615787f.png)
![dos50](https://user-images.githubusercontent.com/5713395/132363355-4fc01986-1bdf-4f0a-a693-a0d339156e75.png)
[check-fcb.zip](https://github.com/dmsc/emu2/files/7122306/check-fcb.zip)
