### ISSUE TITLE
Minor cursor positioning issues with BRE v0.998

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#48]
* [Barren Realms Elite v0.998](https://www.johndaileysoftware.com/products/bbsdoors/barrenrealmselite) has some odd cursor positioning problems, always coming to rest up one line and to the left of the proper location.
* Sometimes new output incorrectly overwrites old or doesn't scroll correctly.

**Comment by dmsc** [comment]
Hi,

That game moves the cursor writing directly to the video CRTC registers, instead of doing video calls. This won't work in some old PC compatible computers, and it is the first app I see that actually does this.

I already was emulating the CRTC cursor location register, but ignoring the value, I updated the code to actually use that. I tested a few apps and it seems to work ok.
